### ISSUE TITLE
Feature Request Linked Repeaters

### ISSUE THREAD

**Issue by kg6sjt** [hardaker/simplexmap#4]
Is there a way that linked repeaters could be indicated. The case I'm looking at for the Red Cross is that Shasta ARES is able to connect to the W6ECE repeater, but that is linked to the n6ICW repeater. be nice if on the may you click on the repeater, it showed a link to the repeater it is link to so you know the signal get to the next location.

**Comment by hardaker** [comment]
Ohhh...  good point.  And K6JRB and W6AK have a link too.  We should probably distinguish between "always linked" and "sometimes linked"?

**Comment by kg6sjt** [comment]
Good point. 
Thanks
Greg

---

Greg Kruckewitt, KG6SJT
ARRL Sacramento Valley Section
District 3 Emergency Coordinator
kg6sjt@gmail.com
www.sacvalleyares.org
530-219-0611 cell
530-746-8426 Google Voice

MSG. via packet BBS: kg6sjt@ag6qo.#nca.ca.usa.noam

**Comment by hardaker** [comment]
Added support behind the scenes for making it happen, but no UI is present yet.

**Comment by kg6sjt** [comment]
Thank you.. Really nice here in pioneer.
I will be at the Red Cross shelter in Pioneer for the exercise I believe..
Unless they need to move me.

Talk to you soon.

## Greg

Greg Kruckewitt, KG6SJT
ARRL Sacramento Valley Section
District 3 Emergency Coordinator
kg6sjt@gmail.com
www.sacvalleyares.org

530-219-0611 cell
530-746-8426 Google Voice

MSG. via packet BBS: kg6sjt@ag6qo.#nca.ca.usa.noam

**Comment by hardaker** [comment]
When you create a new station, there is now a drop down menu to let you select between station types and right now these contain:

1) a home station
2) a red cross station

The infrastructure is there, but I need to manually add any new stations we want (because of the need to draw icons for them).  Any others you can think of that we should have?  If so, submit a new feature request (or send me email).

I'll close this one as done.  However, editing still isn't possible to change old stations.  That's a separate problem :-P
